Instructions for creating a conda enviroment with python3.8.8
CBICA/NiBAx pull request #181
Opened 2022-03-09 17:46 UTC by melhemr

… #160

2022-03-09 18:07 UTC, melhemr commented
@AbdulkadirA 

The only line I wasn't entirely sure how to deal with this line since I am using a mac: 

### Prepare environment for PowerShell (Windows 10 or 11)
Assuming conda enviroment with Python version 3.8.8 has been created

```shell
**& env/Scripts/Activate.ps1**
python -m pip install --upgrade pip
poetry install
```

In these instructions, I've outlined it so the users create a conda enviroment, so I'm not sure where or how the ```& env/Scripts/Activate.ps1``` should be implemented for Windows users. Can you let me know?

2022-03-09 19:42 UTC, ashishsingh18 commented
> 
@melhemr In my conda env, I usually just do:
`python -m pip install -U -e .`
`poetry install`

2022-03-09 19:49 UTC, ashishsingh18 commented
It might be clearer if we create 2 separate sections for installation: one using conda and the other using virtual env.

2022-03-11 13:19 UTC, AbdulkadirA requested changes
@melhemr Thanks. I made some suggestions.

2022-03-11 13:19 UTC, AbdulkadirA commented on README.md
> +Assuming conda enviroment with Python version 3.8.8 has been created
```suggestion
Assuming conda enviroment with Python version 3.8.8 or newer has been created
```

2022-03-11 13:19 UTC, AbdulkadirA commented on README.md
> +Assuming conda enviroment with Python version 3.8.8 has been created
```suggestion
Assuming conda enviroment with Python version 3.8.8 or newer has been created
```

2022-03-11 13:19 UTC, AbdulkadirA commented on README.md
> +conda create -n env python=3.8.8
Calling the environment `env` may be misleading. I think it is much better to call the environment `NiBAx`.

2022-03-11 13:19 UTC, AbdulkadirA commented on README.md
> +python --version # should be 3.8.8
```suggestion
python --version # should be 3.8.8 or newer
```

2022-03-11 13:20 UTC, AbdulkadirA reviewed
And one more comment ..

2022-03-11 13:20 UTC, AbdulkadirA commented on README.md
> +Install Python version 3.8.8.
```suggestion
Install Python version 3.8.8 or newer.
```

2022-05-26 14:46 UTC, AbdulkadirA requested changes
@melhemr Thanks. Please leave the sections on setting up the PIP venv for Windows and Linux as they were and only add a section for conda. You could add the indication of PIP to the exiting section headers, though.

2022-05-26 14:51 UTC, melhemr commented
> @melhemr Thanks. Please leave the sections on setting up the PIP venv for Windows and Linux as they were and only add a section for conda. You could add the indication of PIP to the exiting section headers, though.

Can you clarify what you mean? I did leave the PIP section alone, and added conda sections as we discussed. Windows for example:

```
### Prepare environment for PowerShell (Windows 10 or 11)
Assuming current working directory is `NiBAx` and containing the source code
cloned from https://github.com/CBICA/NiBAx.git.

Virtual environment
```shell
python -m venv .env
& .env/Scripts/Activate.ps1
python -m pip install --upgrade pip
poetry install
```
```
Conda environment (assuming conda environment with Python version 3.8.8 or newer has been created)
```shell
conda activate NiBAx
python -m pip install --upgrade pip
poetry install
```

2022-05-27 10:45 UTC, AbdulkadirA requested changes
@melhemr I propose a couple of changes to further simplify.

2022-05-27 10:45 UTC, AbdulkadirA commented on README.md
> +Install Python version 3.8.8 or newer. The exact procedure depends on the operating system and configuration. Verify the version with
```suggestion
Install Python version 3.8.8 or newer.
The exact procedure depends on the operating system and configuration.
Verify the version with
```

2022-05-27 10:45 UTC, AbdulkadirA commented on README.md
> +If python environment is not 3.8.8 or newer, use the following instructions to prepare a conda environment with the correct version.
```suggestion
```

2022-05-27 10:45 UTC, AbdulkadirA commented on README.md
> +To create the enviroment:
```suggestion
```

2022-05-27 10:45 UTC, AbdulkadirA commented on README.md
> +```shell
```suggestion
```

2022-05-27 10:45 UTC, AbdulkadirA commented on README.md
>  desired version, use one of the following commands to install it.
```suggestion
To install the [NiBAx], install it in a virtual or conda environment.
Depending on the desired version, use one of the following
commands to install it.
```

2022-05-27 13:50 UTC, melhemr commented
@AbdulkadirA the changes look good. The only final concern I had is about Ashish's comment above. It seems that using a conda environment with a Windows OS still requires using the command ```poetry install```. I don't know if that's 100% necessary, but if it is, how should we include that in the conda environment section?

2022-05-31 05:22 UTC, AbdulkadirA requested changes
Poetry is generally not required, only to package the toolbox.

2022-05-31 05:22 UTC, AbdulkadirA commented on README.md
>  poetry install
```suggestion
```

2022-05-31 05:28 UTC, AbdulkadirA approved these changes

2022-05-31 05:30 UTC, merged